/**
 * Embeds the two Playwright metadata files the runtime needs on disk.
 *
 * playwright-core resolves them with `require(path.join(__dirname, "..", X))`.
 * Bun bakes `__dirname` in as the *build machine's* absolute path and cannot
 * bundle a computed require, so on any other machine that lookup hits a path
 * that does not exist. We inline the contents here and write them back out at
 * runtime — see src/runtime-shim.ts.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const CORE = path.join(ROOT, "node_modules", "playwright-core");
const OUT_DIR = path.join(ROOT, "src", "generated");
const OUT = path.join(OUT_DIR, "playwrightAssets.ts");

const NEEDED = ["package.json", "browsers.json"];

const assets = {};
for (const name of NEEDED) {
  const file = path.join(CORE, name);
  if (!fs.existsSync(file)) {
    console.error(`gen-assets: missing ${file} — run npm install first.`);
    process.exit(1);
  }
  // Reparse and restringify so the embedded copy is minimal and valid.
  assets[name] = JSON.stringify(JSON.parse(fs.readFileSync(file, "utf8")));
}

const version = JSON.parse(assets["package.json"]).version;

// Five files record the product version, and a mismatch is invisible until a
// user hits it — a binary reporting the wrong version, a DMG whose filename
// disagrees with its contents, or an install-browser hint naming a Playwright
// release that was never bundled. Fail the build instead of shipping the drift.
{
  const read = (...parts) => fs.readFileSync(path.join(ROOT, ...parts), "utf8");
  const jsonVersion = (...parts) => JSON.parse(read(...parts)).version;

  const versionTs = read("src", "version.ts");
  const declared = (re) => re.exec(versionTs)?.[1];

  const expected = jsonVersion("package.json");
  const recorded = {
    "package.json": expected,
    "src/version.ts": declared(/VERSION\s*=\s*"([^"]+)"/),
    "app/package.json": jsonVersion("app", "package.json"),
    "app/src-tauri/tauri.conf.json": jsonVersion("app", "src-tauri", "tauri.conf.json"),
    "app/src-tauri/Cargo.toml": /^version = "([^"]+)"$/m.exec(read("app", "src-tauri", "Cargo.toml"))?.[1],
  };

  const problems = Object.entries(recorded)
    .filter(([, v]) => v !== expected)
    .map(([file, v]) => `${file} says ${v ?? "(unreadable)"}, expected ${expected}`);

  const declaredPw = declared(/PLAYWRIGHT_VERSION\s*=\s*"([^"]+)"/);
  if (declaredPw !== version) {
    problems.push(`src/version.ts PLAYWRIGHT_VERSION ${declaredPw} != installed playwright-core ${version}`);
  }

  if (problems.length) {
    console.error(
      [
        "gen-assets: version mismatch —",
        ...problems.map((p) => `  ${p}`),
        "",
        `Set every file to the same version (package.json is the reference: ${expected}).`,
      ].join("\n"),
    );
    process.exit(1);
  }
  console.log(`gen-assets: version ${expected} consistent across ${Object.keys(recorded).length} files`);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-assets.mjs — do not edit.
// Embedded from playwright-core ${version}.

export const PLAYWRIGHT_CORE_VERSION = ${JSON.stringify(version)};

export const PLAYWRIGHT_ASSETS: Record<string, string> = {
${Object.entries(assets)
  .map(([name, json]) => `  ${JSON.stringify(name)}: ${JSON.stringify(json)},`)
  .join("\n")}
};
`,
);

console.log(`gen-assets: embedded ${NEEDED.join(", ")} from playwright-core ${version}`);
